version: '8.0.36'
services:
 mysql:
    container_name: mysql_server
    image: mysql:8.0.36-debian

    command: --default-authentication-plugin=mysql_native_password

    networks:
      - backend
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./dockers/mysql/data:/var/lib/mysql
  
networks:
 backend:
    external: true
