name: Lint GitHub Actions workflows
on:
  push:
    paths:
      - '.github/workflows/**'

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
      - name: Install actionlint
        run: go install github.com/rhysd/actionlint/cmd/actionlint@latest
      - name: Run actionlint
        run: actionlint