http:
  routers:
    traefik:
      rule: "Host(`traefik.um.localhost`)"
      service: "api@internal"
      tls:
        domains:
          - main: "um.localhost"
            sans:
              - "*.um.localhost"
          - main: "um.local"
            sans:
              - "*.um.local"

tls:
  certificates:
    - certFile: "/etc/certs/um-cert.pem"
      keyFile: "/etc/certs/um-key.pem"
  options:
    default:
      cipherSuites:
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_RSA_WITH_AES_128_GCM_SHA256
        - TLS_RSA_WITH_AES_256_GCM_SHA384